name: 'Hello World Docker Action'
description: 'time to say hello'
inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: world
output:
  time:
    description: current time
runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

