name: Reusable workflow
on: 
  workflow_call:
    inputs:
      a-quien-saludar:
        description: a-quien-saludar
        type: string
        required: true
        default: world
    outputs:
       current-time:
         description: 'The time when greeting.'
         value: ${{ jobs.reusable-job.outputs.current-time }}"
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "Hola ${{inputs.a-quien-saludar}}
      - name: Set time
        id: time
        run:  echo "Fecha y hora=$(date)" >> $GITHUB_OUTPUT  
        
   
